apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logarift.fullname" . }}-frontend
  labels:
    {{- include "logarift.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "logarift.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "logarift.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        {{- with .Values.frontend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "logarift.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          image: {{ include "logarift.image" (dict "root" . "image" .Values.frontend.image) }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 5173
          envFrom:
            - configMapRef:
                name: {{ include "logarift.fullname" . }}-config
          env:
            {{- range $name, $value := .Values.frontend.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- with .Values.frontend.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.frontend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- include "logarift.podScheduling" .Values.frontend | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logarift.fullname" . }}-frontend
  labels:
    {{- include "logarift.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    {{- include "logarift.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
