{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "logarift.fullname" . }}-mongodb
  labels:
    {{- include "logarift.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  serviceName: {{ include "logarift.fullname" . }}-mongodb
  replicas: 1
  selector:
    matchLabels:
      {{- include "logarift.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "logarift.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
        {{- with .Values.mongodb.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.mongodb.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
          {{- with .Values.mongodb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if not .Values.mongodb.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
      {{- include "logarift.podScheduling" .Values.mongodb | nindent 6 }}
  {{- if .Values.mongodb.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: {{ toYaml .Values.mongodb.persistence.accessModes | nindent 10 }}
        {{- with .Values.mongodb.persistence.storageClassName }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size | quote }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logarift.fullname" . }}-mongodb
  labels:
    {{- include "logarift.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
  selector:
    {{- include "logarift.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}
