{{- if or (not .Values.mongodb.external.existingSecret) (not .Values.valkey.external.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logarift.fullname" . }}-connection
  labels:
    {{- include "logarift.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb-uri: {{ default (printf "mongodb://%s-mongodb:27017" (include "logarift.fullname" .)) .Values.mongodb.external.uri | quote }}
  valkey-url: {{ default (printf "valkey://%s-valkey:6379" (include "logarift.fullname" .)) .Values.valkey.external.url | quote }}
{{- end }}
